# Site settings
title: Les Ateliers de Sandrine
description: "Stages de décoration, restauration et bricolage"
baseurl: ""
url: "http://les-ateliers-de-sandrine.fr"

markdown: kramdown

excerpt_separator: '<!--excerpt-->'

sass:
  # loading path from site root
  # default to _sass
  sass_dir: assets/stylesheets

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  # on a typical twitter bootstrap stats are :
  # nested 138,7kB, compact 129,1kB, expanded 135,9 kB, compressed 122,4 kB
  style: nested

permalink: pretty

emptyArray: []

responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/_responsive-image.html

  # [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 80

  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 800
    - width: 1000
      quality: 80

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images.
  #
  # Parameters available are:
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: assets/resized/%{width}/%{basename}

